changes

diff --git a/template.yaml b/template.yaml
--- a/template.yaml
+++ b/template.yaml
@@ -125,11 +125,22 @@ Resources:
         - !Ref WebServerSecurityGroup
       SubnetId: !Ref PublicSubnet
       IamInstanceProfile: !Ref InstanceProfile
+      KeyName: 'demo-keypair'
       UserData:
         Fn::Base64: |
           #!/bin/bash -xe
           yum update -y
-          yum install -y httpd php php-mysqlnd php-gd php-xml wget curl unzip zip mysql
+          yum install -y httpd php php-mysqlnd php-gd php-xml wget curl unzip zip mysql policycoreutils-python-utils
+          
+          setsebool -P httpd_can_network_connect_db 1 || {
+              echo "Failed to set SELinux boolean"
+              exit 1
+          }
+          cd /tmp
+          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+          unzip awscliv2.zip
+          sudo ./aws/install
+
           systemctl start httpd
           systemctl enable httpd
           cd /var/www/html
@@ -143,7 +154,8 @@ Resources:
           sed -i "s/database_name_here/demo_db/g" wp-config.php
           sed -i "s/username_here/${DB_USERNAME}/g" wp-config.php
           sed -i "s/password_here/${DB_PASSWORD}/g" wp-config.php
-          sed -i "s/localhost/`!GetAtt DBInstance.Endpoint.Address`/g" wp-config.php
+          DB_ENDPOINT=$(aws rds describe-db-instances --db-instance-identifier "demo-db-instance" --query "DBInstances[*].Endpoint.Address" --output text)
+          sed -i "s/localhost/${DB_ENDPOINT}/g" wp-config.php
           chown -R apache:apache /var/www/html
           chmod -R 755 /var/www/html
           systemctl restart httpd
@@ -169,4 +181,4 @@ Resources:
         - !Ref DBSecurityGroup
       MultiAZ: false
       AllocatedStorage: 20
-      #DBInstanceIdentifier: "demo-db-instance"
+      DBInstanceIdentifier: "demo-db-instance"
